apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage-env-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: backstage-env-secret
    template:
      engineVersion: v2
      data:
        BACKEND_SECRET: '{{ .backend_secret }}'
        AUTOMATION_SECRET: '{{ .automation_secret | default (randAlphaNum 24) }}'
        ARGOCD_USER: '{{ .argocd_user }}'
        ARGOCD_PASSWORD: '{{ .argocd_password }}'
        AUTH_OIDC_CLIENT_ID: '{{ .auth_oidc_client_id }}'
        AUTH_OIDC_CLIENT_SECRET: '{{ .auth_oidc_client_secret }}'
        KEYCLOAK_CLIENT_ID: '{{ .keycloak_client_id }}'
        KEYCLOAK_CLIENT_SECRET: '{{ .keycloak_client_secret }}'
        GITLAB_TOKEN: '{{ .gitlab_token }}'
        QUAY_API_TOKEN: '{{ .quay_api_token }}'
        K8S_SERVICEACCOUNT_TOKEN: '{{ .k8s_serviceaccount_token }}'
  dataFrom:
    - extract:
        key: kv/rhads-dh
